name: ECE225_FA24

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.9.5
  - pip
  - jupyter==1.1.1
  - notebook==6.5.6
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn

# python -m ipykernel install --user --name=ECE225_FA24